name: agent3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - langchain==0.3.27
      - langgraph==0.2.53
      - langchain-anthropic==0.3.0
      - pysqa
      - autocat
prefix: /nfs/turbo/coe-venkvis/ziqiw-turbo/conda
